# Generated by Django 4.2.4 on 2023-08-25 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_languages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Languages',
        ),
    ]
