# Generated by Django 4.2.4 on 2023-08-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_languages_about_is_active_contact_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='live_demo_link',
            field=models.TextField(blank=True, default='https://github.com/', null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='source_code_link',
            field=models.TextField(blank=True, default='https://github.com/', null=True),
        ),
    ]
