# Generated by Django 4.2.4 on 2023-08-29 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0006_message_date_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introduction',
            name='description',
        ),
        migrations.AddField(
            model_name='introduction',
            name='description1',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='introduction',
            name='description2',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='introduction',
            name='description3',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='introduction',
            name='description4',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_send',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 29, 11, 16, 33, 66617)),
        ),
    ]
