# Generated by Django 4.2.4 on 2023-08-29 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0007_remove_introduction_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='resume_link',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_send',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 29, 11, 18, 11, 450054)),
        ),
    ]
